# Generated by Django 5.2.5 on 2025-08-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("otp_secret", models.CharField(max_length=100)),
                ("otp_created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User OTP",
                "verbose_name_plural": "User OTPs",
                "db_table": "user_otp",
            },
        ),
    ]
