# Generated by Django 4.2.9 on 2025-08-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userotp",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
