# Generated by Django 4.2.9 on 2025-08-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms_manager", "0002_alter_userotp_phone_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userotp",
            unique_together={("phone_number", "otp_secret")},
        ),
    ]
