# Generated by Django 5.2.5 on 2025-08-15 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("did", models.IntegerField()),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "db_table": "districts",
            },
        ),
        migrations.CreateModel(
            name="Mandal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("mid", models.IntegerField()),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandals",
                        to="booking.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandal",
                "verbose_name_plural": "Mandals",
                "db_table": "mandals",
            },
        ),
        migrations.CreateModel(
            name="MandalVillage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("vid", models.IntegerField()),
                (
                    "mandal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="booking.mandal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandal Village",
                "verbose_name_plural": "Mandal Villages",
                "db_table": "mandal_villages",
            },
        ),
        migrations.CreateModel(
            name="StockYard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "contact_person_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "contact_person_number",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "sand_quality",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("sand_price", models.FloatField(blank=True, null=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_yards",
                        to="booking.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Yard",
                "verbose_name_plural": "Stock Yards",
                "db_table": "stock_yards",
            },
        ),
    ]
