# Generated by Django 5.2.5 on 2025-08-15 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingUserCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=250, unique=True)),
                ("password", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "Booking User List",
                "verbose_name_plural": "Booking User Lists",
                "db_table": "booking_user_list",
            },
        ),
        migrations.CreateModel(
            name="BookingMasterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("gstin", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "sand_purpose",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("vehicle_no", models.CharField(max_length=250)),
                ("delivery_slot", models.CharField(max_length=250)),
                ("payment_mode", models.CharField(max_length=250)),
                (
                    "delivery_district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_master_data_delivery",
                        to="booking.district",
                    ),
                ),
                (
                    "delivery_mandal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_master_data_delivery",
                        to="booking.mandal",
                    ),
                ),
                (
                    "delivery_village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_master_data_delivery",
                        to="booking.mandalvillage",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_master_data",
                        to="booking.district",
                    ),
                ),
                (
                    "stockyard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_master_data",
                        to="booking.stockyard",
                    ),
                ),
                (
                    "booking_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_user_credential",
                        to="booking.bookingusercredential",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Master Data",
                "verbose_name_plural": "Booking Master Data",
                "db_table": "booking_master_data",
            },
        ),
    ]
