# Generated by Django 5.2.5 on 2025-08-17 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_bookingusercredential_bookingmasterdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("proxy", models.CharField(blank=True, max_length=250, null=True)),
                ("status", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "booking_master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_history",
                        to="booking.bookingmasterdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking History",
                "verbose_name_plural": "Booking History",
                "db_table": "booking_history",
            },
        ),
    ]
