# Generated by Django 4.2.9 on 2025-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_bookinghistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinghistory",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
