# Generated by Django 5.2.5 on 2025-08-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_bookinghistory_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockyard",
            name="address",
        ),
        migrations.RemoveField(
            model_name="stockyard",
            name="contact_person_name",
        ),
        migrations.RemoveField(
            model_name="stockyard",
            name="contact_person_number",
        ),
        migrations.AddField(
            model_name="stockyard",
            name="availabe_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
