# Generated by Django 5.2.5 on 2025-08-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_remove_stockyard_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockyard",
            name="sand_price",
        ),
        migrations.AlterField(
            model_name="stockyard",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
